services:
  - type: web
    name: movie-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.headless true
